Responsiveness changes
neobase-one/safe-react pull request #20
Opened 2022-12-02 20:47 UTC by 0xAryanShah

## What it solves
######Notification popup has to be adjusted		
		Use Mobile App Popup Make Green text on black.
		New Transaction popup : Contract Interaction button, Logos can be made black
		Queued transactions will appear here : text smaller even the SVG
		Transactions/History : Filter Text and Whole Filter Popup[Remove it for mobile]		
		Address Book-> Create Entry : The Box has to fit in the page.
		Address Book-> Import Boxes has to fit in.
		Address Book-> Export Boxes has to fit in
		Settings Contract Version popup opening gnosis git contracts
		Remove safe: box has to fit in.
		New Owner : box has to fit in.
		Notification Icon in Center
		Assets: Send and receive buttons are not seen, format the table too.
		Address Book : The Edit/Da1ete/Send button is not seen.
		Settings -> Owners Edit owner/replace owner is not seen. and formatting of the table.
		Assets: No NFTs Available text size
		Address Book: Export Import alignment is off.
		
# Not Done
[Transactions/History : the text can be in line to look continuous]	
		Address Book : Table has to be adjusted
		The Back UX or opening the left panel is not happening if interacted with the page.
		The button are visible but styling them.

2022-12-03 22:38 UTC, akshatcx commented
Lets make another PR for the remaining tasks, that way we can atleast close this. ill add an issue on linear

@SiddarthVijay you can review the PR

2022-12-05 12:47 UTC, SiddarthVijay requested changes

2022-12-05 12:47 UTC, 0xtemujin commented on src/components/Modal/index.tsx
> +  /* border-top: ${({ withoutBorder }) => (withoutBorder ? '0' : '2px')} solid ${({ theme }) =>
Can remove comments

2022-12-05 12:47 UTC, SiddarthVijay commented on src/routes/safe/components/AddressBook/index.tsx
> +              Entry
Leave this as 'Create Entry'

2022-12-05 12:47 UTC, 0xtemujin commented on src/routes/safe/components/Transactions/TxList/styled.tsx
> +  /* &:hover {
Remove comments

2022-12-07 09:13 UTC, SiddarthVijay approved these changes

2022-12-07 09:22 UTC, merged