Feature/can 42 safe remaining mobile responsive tasks
neobase-one/safe-react pull request #21
Opened 2022-12-07 08:04 UTC by 0xAryanShah

## What it solves
Fixed All the Hidden Button Style,
Create Safe Page : Successful msg fixed.

# Pending
Making Address Smaller like :-  ( 0xab3.......yh8w )

2022-12-07 09:25 UTC, SiddarthVijay commented
<img width="1427" alt="image" src="https://user-images.githubusercontent.com/31479595/206139738-544997bf-3dd7-4845-b830-893bf19f216e.png">

Transactions -> History -> Filter -> Module based -> Click on dropdown : Fix color

2022-12-07 09:27 UTC, SiddarthVijay commented
<img width="640" alt="image" src="https://user-images.githubusercontent.com/31479595/206140422-b32ac9e8-ff65-4760-9091-a60c6418a5d2.png">
Center download button

2022-12-07 09:29 UTC, 0xtemujin commented
<img width="236" alt="image" src="https://user-images.githubusercontent.com/31479595/206141141-2c1373a8-6795-4b4e-b4cc-67cf66b93fb7.png">
Address modals - fix color for Canto

2022-12-07 18:26 UTC, 0xAryanShah commented
# Resolves
[Transaction Page] : Tx Hash from Transaction Hash 
[Settings> Owners Page] : Adjust Table
[Transactions/History Page] : the text can be in line to look continuous
[Address Book] : Table has to be adjusted
[Global] : Remove 2 components left bottom	
Cancel button hidden on export modal
Same modal white canto.

2022-12-08 06:31 UTC, 0xAryanShah commented
# Resolves
Transactions -> History -> Filter -> Module/Import/export based -> Click on dropdown color change
Address Book Table Adjustment

2022-12-08 06:34 UTC, tushar994 commented
run `yarn add react-use` and push the changes made by that once? on freshly opening this branch and running `yarn install; yarn start`, the app throws the following error `Module not found: Can't resolve 'react-use' in '/Users/tusharjain/blockchain_work/safe-react/src/routes/safe/components/AddressBook'`. 

Not a big issue because when merged into `dev`, since `dev`'s package.json has `"react-use": "^17.4.0"`, it will work. But still in the interest of cleanliness, maybe make this change?

2022-12-10 09:47 UTC, SiddarthVijay requested changes

2022-12-10 09:47 UTC, SiddarthVijay commented on src/components/AppLayout/Sidebar/DebugToggle/index.tsx
> +  //const [enabled = false, setEnabled] = useCachedState<boolean>(LS_USE_PROD_CGW)
If not required, remove code don't leave it as commented

2022-12-10 09:47 UTC, SiddarthVijay commented on src/components/AppLayout/Sidebar/index.tsx
> +      {/* <HelpContainer>
If not required remove code, not leave it as commented

2022-12-10 10:13 UTC, SiddarthVijay approved these changes

2022-12-10 12:11 UTC, merged